/**
 * External Dependencies
 */
import React from 'react';
import { storiesOf } from '@storybook/react';

/**
 * Internal Dependencies
 */
import { Heading, Text } from '../index';

/**
 * Local Variables
 */
const textStory = storiesOf('Typography', module);

// H1
textStory.add('H1', () => (
  <Heading h1>Heading 1</Heading>
));

// H2
textStory.add('H2', () => (
  <Heading h2>Heading 2</Heading>
));

// H3
textStory.add('H3', () => (
  <Heading h3>Heading 3</Heading>
));

// H4
textStory.add('H4', () => (
  <Heading h4>Heading 4</Heading>
));

// H5
textStory.add('H5', () => (
  <Heading h5>Heading 5</Heading>
));

// Text
textStory.add('Text', () => (
  <Text fontSize={16} color="dark" weight={900}>
    This is a paragraph about really nothing. Because life is nothing. It's not real. It does not exist. We're just in a computer simulation.
    <br /><br />
    It is true. We're living in a simulation generated by someone or something. But the scarier part is ... who created them? Are they in a simulation? If so, who created them?
  </Text>
));

// Heading with Text
textStory.add('Heading with Text', () => (
  <React.Fragment>
    <Heading h3>Hello, World!</Heading>
    <Text color="base">
      This is a demo app. We're using Storybook to test components.
    </Text>
  </React.Fragment>
));
