/**
 * External Dependencies
 */
import React from 'react';
import { storiesOf } from '@storybook/react';
import { action } from '@storybook/addon-actions';

/**
 * Internal Dependencies
 */
import Button from '../src/components/button';
import Row from '../src/components/row';
import Card from '../src/components/card';
import { Heading, Text } from '../src/components/text';
import Image from '../src/components/image';

/**
 * Buttons
 */
storiesOf('Buttons', module)
  .add('Default', () => (
    <Button onClick={action('clicked')}>
      Default Button
    </Button>
  ))
  .add('Invert', () => (
    <Button bg="#222" color="#29ABDA">
      Dark Button
    </Button>
  ))
  .add('Rounded', () => (
    <Button bg="#6155E6" color="#FFF" rounded>
      Rounded Button
    </Button>
  ));

/**
 * Heading and Text
 */
storiesOf('Typography', module)
  .add('Headings', () => (
    <div>
      <Heading h={1}>Heading h1</Heading>
      <Heading h={2}>Heading h2</Heading>
      <Heading h={3}>Heading h3</Heading>
      <Heading h={4}>Heading h4</Heading>
      <Heading h={5}>Heading h5</Heading>
    </div>
  ))
  .add('P', () => (
    <Text fontSize={16} color="dark" weight={900}>
      This is a paragraph about really nothing. Because life is nothing. It's not real. It does not exist. We're just in a computer simulation.
      <br /><br />
      It is true. We're living in a simulation generated by someone or something. But the scarier part is ... who created them? Are they in a simulation? If so, who created them?
    </Text>
  ))
  .add('Heading + P', () => (
    <div>
      <Heading h={3} weight={800} marginBottom>Hello, World!</Heading>
      <Text color="base">
        This is a demo app. We're using Storybook to test components.
      </Text>
    </div>
  ));

/**
 * Cards
 */
storiesOf('Card', module)
  .add('Default Card', () => (
    <Row split="1fr 1fr" gap="2rem" padding="4rem 12.5%" sameHeightChildren>
      <Card bg="gray" padding="2rem" radius="10px">
        <Heading h={5} weight={800} lineHeight={120}>
          How to Publish an npm package
        </Heading>
        <Text lineHeight={135} color="base" fontSize={16} marginBottom="0">
          For those who don't know, npm, also known as node package manager is a package manager where people publish their libraries.
        </Text>
      </Card>
      <Card bg="white" padding="2rem" radius="10px" hasShadow>
        <Heading h={5} weight={800} lineHeight={120}>
          How to Publish an npm package
        </Heading>
        <Text lineHeight={135} color="base" fontSize={16} marginBottom="0">
          For those who don't know, npm, also known as node package manager is a package manager where people publish their libraries.
        </Text>
      </Card>
    </Row>
  ))
  .add('Card w/ Images', () => (
    <Row split="1fr 1fr 1fr" gap="1rem" padding="4rem 12.5%" sameHeightChildren>
      <Card bg="gray" padding="0" radius="10px">
        <Image
          src="https://i.imgur.com/IqFgSfx.jpg"
          radius="10px"
          alt="Layout"
          margin="0 auto"
        />
        <Row split="1fr" padding="1rem 1.5rem">
          <Heading h={5} weight={800}>Layout</Heading>
          <Text lineHeight={125} color="base" fontSize={14}>
            Learn about the layout
          </Text>
        </Row>
      </Card>
      <Card padding="1rem">
        <Image
          src="https://i.imgur.com/VngE8Bf.jpg"
          radius="10px"
          alt="Layout"
          margin="0 auto 1rem"
        />
        <Heading h={5} weight={800}>Typography</Heading>
        <Text lineHeight={125} color="base" fontSize={14}>
          Learn about fonts
        </Text>
      </Card>
      <Card bg="white" padding="1rem" hasShadow>
        <Heading h={5} weight={800}>Colors</Heading>
        <Text lineHeight={125} color="base" fontSize={14} marginBottom="0">
          Learn about the colors
        </Text>
        <Image
          src="https://i.imgur.com/3nCddcl.jpg"
          radius="10px"
          alt="Layout"
          margin="1rem auto 0"
        />
      </Card>
    </Row>
  ));
